name: Demo Environment Secret

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'PROD'
        type: choice
        options:
          - PROD
          - staging

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}
      url: https://example.com

    steps:
      - name: Print environment name
        run: echo "Environment is: ${{ inputs.environment }}"

      - name: Use PROD_API_KEY
        run: echo "Prod API key is: ${{ secrets.PROD_API_KEY }}"
